<?xml version="1.0" encoding="utf-8"?><Database Name="galaxyenclave" Class="WebsiteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=mssql.tweakhere.com,1533;Initial Catalog=galaxyenclave;Persist Security Info=True;User ID=tweakhere_insti" SettingsObjectName="BusinessLogicLayer.Properties.Settings" SettingsPropertyName="WebsiteConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ABUser_login" Member="ABUser_logins">
    <Type Name="ABUser_login">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmailID" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ProfileImage" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SessionID" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryList" Member="CategoryLists">
    <Type Name="CategoryList">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ApplyFor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AllotmentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.ABPrc_AdminDashboard" Method="ABPrc_AdminDashboard">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="ABPrc_AdminDashboardResult">
      <Column Name="TotalApplication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="PaidApplication" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ABPrc_CreateOrderNumber" Method="ABPrc_CreateOrderNumber">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="ABPrc_CreateOrderNumberResult">
      <Column Name="OrderNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ABproc_CheckuserLogin" Method="ABproc_CheckuserLogin">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IPAddress" Parameter="iPAddress" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="ABproc_CheckuserLoginResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Settle" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Balance" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BalanceAmount" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="LoginResult" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_AddEditContactList" Method="Prc_AddEditContactList">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="CustomerName" Parameter="customerName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SrNo" Parameter="srNo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Father" Parameter="father" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RegNo" Parameter="regNo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Alloty" Parameter="alloty" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Status" Parameter="status" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Output" Parameter="output" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_AddEditRegister" Method="Prc_AddEditRegister">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="ApplyFor" Parameter="applyFor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Contact" Parameter="contact" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Email_ID" Parameter="email_ID" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DOB" Parameter="dOB" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Relation" Parameter="relation" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RelationName" Parameter="relationName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IDName" Parameter="iDName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IDValues" Parameter="iDValues" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="AadhaarNumber" Parameter="aadhaarNumber" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="AccountHolderName" Parameter="accountHolderName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="BankAccountNumber" Parameter="bankAccountNumber" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="BankName" Parameter="bankName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IFSCCode" Parameter="iFSCCode" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="BankAddress" Parameter="bankAddress" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="AnnulIncome" Parameter="annulIncome" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="Country" Parameter="country" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="State" Parameter="state" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Pincode" Parameter="pincode" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="InsertDate" Parameter="insertDate" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DDNo" Parameter="dDNo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DDAmount" Parameter="dDAmount" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Output" Parameter="output" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_AdminPanelMenu" Method="Prc_AdminPanelMenu">
    <Parameter Name="ParentMenuID" Parameter="parentMenuID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_AdminPanelMenuResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PageName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Show" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_AdminPanelPageCreatePermission" Method="Prc_AdminPanelPageCreatePermission">
    <Parameter Name="PageName" Parameter="pageName" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="PageURL" Parameter="pageURL" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_AdminPanelPageList" Method="Prc_AdminPanelPageList">
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_AdminPanelPageListResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PageName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PermissionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_AdminPanelPagePermissionCheck" Method="Prc_AdminPanelPagePermissionCheck">
    <Parameter Name="PageURL" Parameter="pageURL" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_AdminPanelPagePermissionCheckResult">
      <Column Name="PermissionStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_CategoryList" Method="Prc_CategoryList">
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="ApplyFor" Parameter="applyFor" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="Prc_CategoryListResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ApplyFor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AllotmentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_CategoryWiseApplication" Method="Prc_CategoryWiseApplication">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_CategoryWiseApplicationResult">
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="EWSCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LIGCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_CategoryWisePlotAllotment" Method="Prc_CategoryWisePlotAllotment">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_CategoryWisePlotAllotmentResult">
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="EWSCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LIGCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_ContactList" Method="Prc_ContactList">
    <Parameter Name="SearchBy" Parameter="searchBy" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ApplyFor" Parameter="applyFor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Alloty" Parameter="alloty" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_ContactListResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SrNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RelationName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RegNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Alloty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PlotNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RegID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AadhaarNumber" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FormStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RejectRemark" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ApplyFor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Relation" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_Create_OrderNumber" Method="Prc_Create_OrderNumber">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_Create_OrderNumberResult">
      <Column Name="OrderNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_Create_OrderSummary" Method="Prc_Create_OrderSummary">
    <Parameter Name="CustomerID" Parameter="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RegID" Parameter="regID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FormID" Parameter="formID" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Order_ID" Parameter="order_ID" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Total_Price" Parameter="total_Price" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="Payment_Status" Parameter="payment_Status" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AmountReceived" Parameter="amountReceived" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="RefundAmount" Parameter="refundAmount" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="RefundDetail" Parameter="refundDetail" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="insertDate" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PaymentDate" Parameter="paymentDate" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RefundDate" Parameter="refundDate" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SessionID" Parameter="sessionID" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_DeleteContactList" Method="Prc_DeleteContactList">
    <Parameter Name="SearchBy" Parameter="searchBy" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_DisctinctLotteryNo" Method="Prc_DisctinctLotteryNo">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_DisctinctLotteryNoResult">
      <Column Name="TrialNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_FormCategoryDisctinct" Method="Prc_FormCategoryDisctinct">
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="Prc_FormCategoryDisctinctResult">
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_Formlist" Method="Prc_Formlist">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="SearchBy" Parameter="searchBy" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="ApplyFor" Parameter="applyFor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RegNo" Parameter="regNo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Alloty" Parameter="alloty" Type="System.Int32" DbType="Int" />
    <Parameter Name="FormStatus" Parameter="formStatus" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_FormlistResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SrNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RelationName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RegNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Alloty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PlotNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RegID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RejectRemark" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="PlotCategory" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ApplicantCategory" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_FormListCategoryWise" Method="Prc_FormListCategoryWise">
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SearchBy" Parameter="searchBy" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FormStatus" Parameter="formStatus" Type="System.Int32" DbType="Int" />
    <Parameter Name="Alloty" Parameter="alloty" Type="System.Int32" DbType="Int" />
    <Parameter Name="FormNo" Parameter="formNo" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_FormListCategoryWiseResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SrNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Father" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RegNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Alloty" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RegID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RejectRemark" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="PlotNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PlotCategory" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ApplicantCategory" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_FormlistExport" Method="Prc_FormlistExport">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="SearchBy" Parameter="searchBy" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="ApplyFor" Parameter="applyFor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RegNo" Parameter="regNo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Alloty" Parameter="alloty" Type="System.Int32" DbType="Int" />
    <Parameter Name="FormStatus" Parameter="formStatus" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_FormlistExportResult">
      <Column Name="RowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="RegNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RelationName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MobileNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PlotCategory" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ApplicantCategory" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FormStatus" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="RejectRemark" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_GeneralSettingDetails" Method="Prc_GeneralSettingDetails">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_GeneralSettingDetailsResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsFinalLottery" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NextLotteryTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_RegisterList" Method="Prc_RegisterList">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="SearchBy" Parameter="searchBy" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="ApplyFor" Parameter="applyFor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PaymentStatus" Parameter="paymentStatus" Type="System.Int32" DbType="Int" />
    <Parameter Name="DDStatus" Parameter="dDStatus" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_RegisterListResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Relation" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RelationName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IDName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IDValues" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AadhaarNumber" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AnnulIncome" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pincode" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="insertDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ApplyFor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Payment_Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DDAmount" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="DDNumber" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DDReturnToName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DDReturnIDName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DDReturnIDValue" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DDReturn" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DDReturnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_ResetTrialLottery" Method="Prc_ResetTrialLottery">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_TrailNoListWithSeed" Method="Prc_TrailNoListWithSeed">
    <Parameter Name="TrialNo" Parameter="trialNo" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="Prc_TrailNoListWithSeedResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrialNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SeedNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_TrailNoWithSeedAdd" Method="Prc_TrailNoWithSeedAdd">
    <Parameter Name="TrialNo" Parameter="trialNo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SeedNo" Parameter="seedNo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Output" Parameter="output" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_Transactionlist" Method="Prc_Transactionlist">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="PaymentStatus" Parameter="paymentStatus" Type="System.Int32" DbType="Int" />
    <Parameter Name="FormID" Parameter="formID" Type="System.Int32" DbType="Int" />
    <Parameter Name="OrderID" Parameter="orderID" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="SearchBy" Parameter="searchBy" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ApplyFor" Parameter="applyFor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RegID" Parameter="regID" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_TransactionlistResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Order_ID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Total_Price" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="Payment_Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AmountReceived" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="RefundAmount" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="RefundDetail" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="insertDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PaymentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RefundDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IDName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IDValues" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AadhaarNumber" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AnnulIncome" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pincode" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="insertDate1" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ApplyFor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RelationName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Relation" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AccountHolderName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IFSCCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BankAddress" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="DDAmount" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="DDNumber" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BankAccountNumber" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DDReturnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DDReturnToName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DDReturnIDName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DDReturnIDValue" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DDDepositer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DDDepositerID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DDDepositerIDNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DDDepositorRelation" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_TrialLotteryList" Method="Prc_TrialLotteryList">
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PlotCategory" Parameter="plotCategory" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TrialNo" Parameter="trialNo" Type="System.Int32" DbType="Int" />
    <ElementType Name="Prc_TrialLotteryListResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Father" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RegNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PlotNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PlotCategory" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ApplicantCategory" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TrialNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Prc_UpdateAmount" Method="Prc_UpdateAmount">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="Amount" Parameter="amount" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_UpdateDDAmount" Method="Prc_UpdateDDAmount">
    <Parameter Name="RegID" Parameter="regID" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="AccountHolderName" Parameter="accountHolderName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="BankName" Parameter="bankName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="BankAccountNumber" Parameter="bankAccountNumber" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IFSCCode" Parameter="iFSCCode" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="BankAddress" Parameter="bankAddress" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DDAmount" Parameter="dDAmount" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="DDNumber" Parameter="dDNumber" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DDDepositer" Parameter="dDDepositer" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DDDepositerID" Parameter="dDDepositerID" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DDDepositerIDNo" Parameter="dDDepositerIDNo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DDDepositorRelation" Parameter="dDDepositorRelation" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="OutPut" Parameter="outPut" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_UpdateDDReturn" Method="Prc_UpdateDDReturn">
    <Parameter Name="RegID" Parameter="regID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DDReturnToName" Parameter="dDReturnToName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DDReturnIDName" Parameter="dDReturnIDName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DDReturnIDValue" Parameter="dDReturnIDValue" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DDReturn" Parameter="dDReturn" Type="System.Int32" DbType="Int" />
    <Parameter Name="OutPut" Parameter="outPut" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_UpdatePagePermission" Method="Prc_UpdatePagePermission">
    <Parameter Name="PermissionID" Parameter="permissionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_UpdatePaymentStatus" Method="Prc_UpdatePaymentStatus">
    <Parameter Name="OrderID" Parameter="orderID" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Txn_id" Parameter="txn_id" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Payer_Email" Parameter="payer_Email" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="CardType" Parameter="cardType" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PaymentType" Parameter="paymentType" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="PaymentStatus" Parameter="paymentStatus" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="xBatch" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="xRefNum" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="xName" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="xMaskedCardNumber" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Employee" Parameter="employee" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Amount" Parameter="amount" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="CustomerName" Parameter="customerName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Father" Parameter="father" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FormNo" Parameter="formNo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RegId" Parameter="regId" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_UpdateRandomCustomerAlloty" Method="Prc_UpdateRandomCustomerAlloty">
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="ApplyFor" Parameter="applyFor" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_UpdateRejectRemark" Method="Prc_UpdateRejectRemark">
    <Parameter Name="RegID" Parameter="regID" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RejectRemark" Parameter="rejectRemark" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="FormStatus" Parameter="formStatus" Type="System.Int32" DbType="Int" />
    <Parameter Name="OutPut" Parameter="outPut" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_UpdateSetLotteryTimer" Method="Prc_UpdateSetLotteryTimer">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsFinalLottery" Parameter="isFinalLottery" Type="System.Int32" DbType="Int" />
    <Parameter Name="OutPut" Parameter="outPut" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Prc_CheckSeedNo" Method="Prc_CheckSeedNo">
    <Parameter Name="SeedNo" Parameter="seedNo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Output" Parameter="output" Type="System.String" DbType="VarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>