#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="galaxyenclave")]
	public partial class WebsiteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public WebsiteDataContext() : 
				base(global::BusinessLogicLayer.Properties.Settings.Default.WebsiteConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WebsiteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebsiteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebsiteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebsiteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ABUser_login> ABUser_logins
		{
			get
			{
				return this.GetTable<ABUser_login>();
			}
		}
		
		public System.Data.Linq.Table<CategoryList> CategoryLists
		{
			get
			{
				return this.GetTable<CategoryList>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ABPrc_AdminDashboard")]
		public ISingleResult<ABPrc_AdminDashboardResult> ABPrc_AdminDashboard([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<ABPrc_AdminDashboardResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ABPrc_CreateOrderNumber")]
		public ISingleResult<ABPrc_CreateOrderNumberResult> ABPrc_CreateOrderNumber([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<ABPrc_CreateOrderNumberResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ABproc_CheckuserLogin")]
		public ISingleResult<ABproc_CheckuserLoginResult> ABproc_CheckuserLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(100)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(100)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IPAddress", DbType="VarChar(50)")] string iPAddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, password, iPAddress);
			return ((ISingleResult<ABproc_CheckuserLoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_AddEditContactList")]
		public int Prc_AddEditContactList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerName", DbType="VarChar(100)")] string customerName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SrNo", DbType="VarChar(50)")] string srNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Father", DbType="VarChar(100)")] string father, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegNo", DbType="VarChar(50)")] string regNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Alloty", DbType="Bit")] System.Nullable<bool> alloty, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Bit")] System.Nullable<bool> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Output", DbType="VarChar(200)")] ref string output)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, customerName, srNo, father, regNo, alloty, status, output);
			output = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_AddEditRegister")]
		public int Prc_AddEditRegister(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplyFor", DbType="VarChar(100)")] string applyFor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contact", DbType="VarChar(20)")] string contact, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email_ID", DbType="VarChar(100)")] string email_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(100)")] string gender, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOB", DbType="VarChar(100)")] string dOB, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Relation", DbType="VarChar(100)")] string relation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RelationName", DbType="VarChar(100)")] string relationName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDName", DbType="VarChar(100)")] string iDName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDValues", DbType="VarChar(100)")] string iDValues, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AadhaarNumber", DbType="VarChar(100)")] string aadhaarNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountHolderName", DbType="VarChar(100)")] string accountHolderName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankAccountNumber", DbType="VarChar(100)")] string bankAccountNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankName", DbType="VarChar(100)")] string bankName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IFSCCode", DbType="VarChar(100)")] string iFSCCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(200)")] string category, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankAddress", DbType="VarChar(2000)")] string bankAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AnnulIncome", DbType="VarChar(100)")] string annulIncome, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(2000)")] string address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="NVarChar(50)")] string country, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="NVarChar(50)")] string state, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="NVarChar(50)")] string city, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pincode", DbType="VarChar(100)")] string pincode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InsertDate", DbType="VarChar(100)")] string insertDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDNo", DbType="VarChar(50)")] string dDNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDAmount", DbType="Decimal(12,2)")] System.Nullable<decimal> dDAmount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Output", DbType="VarChar(200)")] ref string output)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, applyFor, name, contact, email_ID, gender, dOB, relation, relationName, iDName, iDValues, aadhaarNumber, accountHolderName, bankAccountNumber, bankName, iFSCCode, category, bankAddress, annulIncome, address, country, state, city, pincode, insertDate, dDNo, dDAmount, status, output);
			output = ((string)(result.GetParameterValue(28)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_AdminPanelMenu")]
		public ISingleResult<Prc_AdminPanelMenuResult> Prc_AdminPanelMenu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentMenuID", DbType="Int")] System.Nullable<int> parentMenuID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminID", DbType="Int")] System.Nullable<int> adminID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parentMenuID, adminID);
			return ((ISingleResult<Prc_AdminPanelMenuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_AdminPanelPageCreatePermission")]
		public int Prc_AdminPanelPageCreatePermission([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageName", DbType="VarChar(200)")] string pageName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageURL", DbType="VarChar(200)")] string pageURL)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageName, pageURL);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_AdminPanelPageList")]
		public ISingleResult<Prc_AdminPanelPageListResult> Prc_AdminPanelPageList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminID", DbType="Int")] System.Nullable<int> adminID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), status, adminID);
			return ((ISingleResult<Prc_AdminPanelPageListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_AdminPanelPagePermissionCheck")]
		public ISingleResult<Prc_AdminPanelPagePermissionCheckResult> Prc_AdminPanelPagePermissionCheck([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageURL", DbType="VarChar(200)")] string pageURL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminID", DbType="Int")] System.Nullable<int> adminID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageURL, adminID);
			return ((ISingleResult<Prc_AdminPanelPagePermissionCheckResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_CategoryList")]
		public ISingleResult<Prc_CategoryListResult> Prc_CategoryList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(200)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplyFor", DbType="VarChar(100)")] string applyFor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category, applyFor);
			return ((ISingleResult<Prc_CategoryListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_CategoryWiseApplication")]
		public ISingleResult<Prc_CategoryWiseApplicationResult> Prc_CategoryWiseApplication([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<Prc_CategoryWiseApplicationResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_CategoryWisePlotAllotment")]
		public ISingleResult<Prc_CategoryWisePlotAllotmentResult> Prc_CategoryWisePlotAllotment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<Prc_CategoryWisePlotAllotmentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_ContactList")]
		public ISingleResult<Prc_ContactListResult> Prc_ContactList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchBy", DbType="VarChar(100)")] string searchBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(100)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplyFor", DbType="VarChar(100)")] string applyFor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Alloty", DbType="Int")] System.Nullable<int> alloty, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] System.Nullable<int> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchBy, category, applyFor, alloty, status);
			return ((ISingleResult<Prc_ContactListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_Create_OrderNumber")]
		public ISingleResult<Prc_Create_OrderNumberResult> Prc_Create_OrderNumber([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Prc_Create_OrderNumberResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_Create_OrderSummary")]
		public int Prc_Create_OrderSummary([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegID", DbType="Int")] System.Nullable<int> regID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormID", DbType="VarChar(200)")] string formID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Order_ID", DbType="VarChar(200)")] string order_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total_Price", DbType="Decimal(12,2)")] System.Nullable<decimal> total_Price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Payment_Status", DbType="Bit")] System.Nullable<bool> payment_Status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AmountReceived", DbType="Decimal(12,2)")] System.Nullable<decimal> amountReceived, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RefundAmount", DbType="Decimal(12,2)")] System.Nullable<decimal> refundAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RefundDetail", DbType="VarChar(2000)")] string refundDetail, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string insertDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentDate", DbType="VarChar(100)")] string paymentDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RefundDate", DbType="VarChar(100)")] string refundDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessionID", DbType="VarChar(100)")] string sessionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID, regID, formID, order_ID, total_Price, payment_Status, amountReceived, refundAmount, refundDetail, insertDate, paymentDate, refundDate, sessionID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_DeleteContactList")]
		public int Prc_DeleteContactList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchBy", DbType="VarChar(100)")] string searchBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_DisctinctLotteryNo")]
		public ISingleResult<Prc_DisctinctLotteryNoResult> Prc_DisctinctLotteryNo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<Prc_DisctinctLotteryNoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_FormCategoryDisctinct")]
		public ISingleResult<Prc_FormCategoryDisctinctResult> Prc_FormCategoryDisctinct([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(100)")] string category)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category);
			return ((ISingleResult<Prc_FormCategoryDisctinctResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_Formlist")]
		public ISingleResult<Prc_FormlistResult> Prc_Formlist([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchBy", DbType="VarChar(100)")] string searchBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(200)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplyFor", DbType="VarChar(100)")] string applyFor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegNo", DbType="Int")] System.Nullable<int> regNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Alloty", DbType="Int")] System.Nullable<int> alloty, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormStatus", DbType="Int")] System.Nullable<int> formStatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, searchBy, category, applyFor, regNo, alloty, formStatus);
			return ((ISingleResult<Prc_FormlistResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_FormListCategoryWise")]
		public ISingleResult<Prc_FormListCategoryWiseResult> Prc_FormListCategoryWise([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(100)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchBy", DbType="VarChar(100)")] string searchBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormStatus", DbType="Int")] System.Nullable<int> formStatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Alloty", DbType="Int")] System.Nullable<int> alloty, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormNo", DbType="Int")] System.Nullable<int> formNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category, searchBy, formStatus, alloty, formNo);
			return ((ISingleResult<Prc_FormListCategoryWiseResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_FormlistExport")]
		public ISingleResult<Prc_FormlistExportResult> Prc_FormlistExport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchBy", DbType="VarChar(100)")] string searchBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(200)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplyFor", DbType="VarChar(100)")] string applyFor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegNo", DbType="Int")] System.Nullable<int> regNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Alloty", DbType="Int")] System.Nullable<int> alloty, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormStatus", DbType="Int")] System.Nullable<int> formStatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, searchBy, category, applyFor, regNo, alloty, formStatus);
			return ((ISingleResult<Prc_FormlistExportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_GeneralSettingDetails")]
		public ISingleResult<Prc_GeneralSettingDetailsResult> Prc_GeneralSettingDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<Prc_GeneralSettingDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_RegisterList")]
		public ISingleResult<Prc_RegisterListResult> Prc_RegisterList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchBy", DbType="VarChar(500)")] string searchBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplyFor", DbType="VarChar(100)")] string applyFor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(100)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentStatus", DbType="Int")] System.Nullable<int> paymentStatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDStatus", DbType="Int")] System.Nullable<int> dDStatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, searchBy, applyFor, category, paymentStatus, dDStatus);
			return ((ISingleResult<Prc_RegisterListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_ResetTrialLottery")]
		public int Prc_ResetTrialLottery([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_TrailNoListWithSeed")]
		public ISingleResult<Prc_TrailNoListWithSeedResult> Prc_TrailNoListWithSeed([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrialNo", DbType="VarChar(100)")] string trialNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), trialNo);
			return ((ISingleResult<Prc_TrailNoListWithSeedResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_TrailNoWithSeedAdd")]
		public int Prc_TrailNoWithSeedAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrialNo", DbType="VarChar(100)")] string trialNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SeedNo", DbType="VarChar(100)")] string seedNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Output", DbType="VarChar(200)")] ref string output)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), trialNo, seedNo, output);
			output = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_Transactionlist")]
		public ISingleResult<Prc_TransactionlistResult> Prc_Transactionlist([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentStatus", DbType="Int")] System.Nullable<int> paymentStatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormID", DbType="Int")] System.Nullable<int> formID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="VarChar(200)")] string orderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchBy", DbType="VarChar(100)")] string searchBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(100)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplyFor", DbType="VarChar(100)")] string applyFor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegID", DbType="Int")] System.Nullable<int> regID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, paymentStatus, formID, orderID, searchBy, category, applyFor, regID);
			return ((ISingleResult<Prc_TransactionlistResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_TrialLotteryList")]
		public ISingleResult<Prc_TrialLotteryListResult> Prc_TrialLotteryList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(100)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlotCategory", DbType="VarChar(100)")] string plotCategory, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrialNo", DbType="Int")] System.Nullable<int> trialNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category, plotCategory, trialNo);
			return ((ISingleResult<Prc_TrialLotteryListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_UpdateAmount")]
		public int Prc_UpdateAmount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="VarChar(100)")] string orderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Decimal(12,2)")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Decimal(12,2)")] System.Nullable<decimal> amount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID, price, amount);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_UpdateDDAmount")]
		public int Prc_UpdateDDAmount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegID", DbType="VarChar(100)")] string regID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountHolderName", DbType="VarChar(100)")] string accountHolderName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankName", DbType="VarChar(100)")] string bankName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankAccountNumber", DbType="VarChar(100)")] string bankAccountNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IFSCCode", DbType="VarChar(100)")] string iFSCCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankAddress", DbType="VarChar(100)")] string bankAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDAmount", DbType="Decimal(12,2)")] System.Nullable<decimal> dDAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDNumber", DbType="VarChar(100)")] string dDNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDDepositer", DbType="VarChar(100)")] string dDDepositer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDDepositerID", DbType="VarChar(100)")] string dDDepositerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDDepositerIDNo", DbType="VarChar(100)")] string dDDepositerIDNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDDepositorRelation", DbType="VarChar(100)")] string dDDepositorRelation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OutPut", DbType="VarChar(200)")] ref string outPut)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), regID, accountHolderName, bankName, bankAccountNumber, iFSCCode, bankAddress, dDAmount, dDNumber, dDDepositer, dDDepositerID, dDDepositerIDNo, dDDepositorRelation, outPut);
			outPut = ((string)(result.GetParameterValue(12)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_UpdateDDReturn")]
		public int Prc_UpdateDDReturn([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegID", DbType="Int")] System.Nullable<int> regID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDReturnToName", DbType="VarChar(100)")] string dDReturnToName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDReturnIDName", DbType="VarChar(100)")] string dDReturnIDName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDReturnIDValue", DbType="VarChar(100)")] string dDReturnIDValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DDReturn", DbType="Int")] System.Nullable<int> dDReturn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OutPut", DbType="VarChar(200)")] ref string outPut)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), regID, dDReturnToName, dDReturnIDName, dDReturnIDValue, dDReturn, outPut);
			outPut = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_UpdatePagePermission")]
		public int Prc_UpdatePagePermission([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermissionID", DbType="Int")] System.Nullable<int> permissionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Int")] System.Nullable<int> isActive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), permissionID, isActive);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_UpdatePaymentStatus")]
		public int Prc_UpdatePaymentStatus(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="VarChar(100)")] string orderID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Txn_id", DbType="VarChar(100)")] string txn_id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Payer_Email", DbType="VarChar(200)")] string payer_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CardType", DbType="VarChar(50)")] string cardType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentType", DbType="VarChar(200)")] string paymentType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PaymentStatus", DbType="VarChar(200)")] string paymentStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string xBatch, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string xRefNum, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string xName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string xMaskedCardNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Employee", DbType="VarChar(200)")] string employee, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Decimal(12,2)")] System.Nullable<decimal> amount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerName", DbType="VarChar(100)")] string customerName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Father", DbType="VarChar(100)")] string father, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormNo", DbType="VarChar(100)")] string formNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegId", DbType="VarChar(100)")] string regId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID, txn_id, payer_Email, cardType, paymentType, paymentStatus, xBatch, xRefNum, xName, xMaskedCardNumber, employee, amount, customerName, father, formNo, regId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_UpdateRandomCustomerAlloty")]
		public int Prc_UpdateRandomCustomerAlloty([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(200)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplyFor", DbType="VarChar(100)")] string applyFor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category, applyFor);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_UpdateRejectRemark")]
		public int Prc_UpdateRejectRemark([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegID", DbType="VarChar(100)")] string regID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RejectRemark", DbType="VarChar(200)")] string rejectRemark, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormStatus", DbType="Int")] System.Nullable<int> formStatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OutPut", DbType="VarChar(200)")] ref string outPut)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), regID, rejectRemark, formStatus, outPut);
			outPut = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_UpdateSetLotteryTimer")]
		public int Prc_UpdateSetLotteryTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsFinalLottery", DbType="Int")] System.Nullable<int> isFinalLottery, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OutPut", DbType="VarChar(200)")] ref string outPut)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, isFinalLottery, outPut);
			outPut = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Prc_CheckSeedNo")]
		public int Prc_CheckSeedNo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SeedNo", DbType="Int")] System.Nullable<int> seedNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Output", DbType="VarChar(200)")] ref string output)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), seedNo, output);
			output = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ABUser_login")]
	public partial class ABUser_login
	{
		
		private int _ID;
		
		private string _UserName;
		
		private string _Password;
		
		private bool _Status;
		
		private bool _IsAdmin;
		
		private string _EmailID;
		
		private string _ProfileImage;
		
		private string _Contact;
		
		private string _SessionID;
		
		public ABUser_login()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit NOT NULL")]
		public bool IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this._IsAdmin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailID", DbType="VarChar(200)")]
		public string EmailID
		{
			get
			{
				return this._EmailID;
			}
			set
			{
				if ((this._EmailID != value))
				{
					this._EmailID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileImage", DbType="VarChar(200)")]
		public string ProfileImage
		{
			get
			{
				return this._ProfileImage;
			}
			set
			{
				if ((this._ProfileImage != value))
				{
					this._ProfileImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(200)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this._Contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionID", DbType="VarChar(200)")]
		public string SessionID
		{
			get
			{
				return this._SessionID;
			}
			set
			{
				if ((this._SessionID != value))
				{
					this._SessionID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CategoryList")]
	public partial class CategoryList
	{
		
		private int _ID;
		
		private string _CategoryName;
		
		private string _ApplyFor;
		
		private int _AllotmentCount;
		
		public CategoryList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="VarChar(200)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyFor", DbType="VarChar(100)")]
		public string ApplyFor
		{
			get
			{
				return this._ApplyFor;
			}
			set
			{
				if ((this._ApplyFor != value))
				{
					this._ApplyFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllotmentCount", DbType="Int NOT NULL")]
		public int AllotmentCount
		{
			get
			{
				return this._AllotmentCount;
			}
			set
			{
				if ((this._AllotmentCount != value))
				{
					this._AllotmentCount = value;
				}
			}
		}
	}
	
	public partial class ABPrc_AdminDashboardResult
	{
		
		private System.Nullable<int> _TotalApplication;
		
		private System.Nullable<decimal> _TotalAmount;
		
		private System.Nullable<decimal> _PaidApplication;
		
		public ABPrc_AdminDashboardResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalApplication", DbType="Int")]
		public System.Nullable<int> TotalApplication
		{
			get
			{
				return this._TotalApplication;
			}
			set
			{
				if ((this._TotalApplication != value))
				{
					this._TotalApplication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				if ((this._TotalAmount != value))
				{
					this._TotalAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaidApplication", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> PaidApplication
		{
			get
			{
				return this._PaidApplication;
			}
			set
			{
				if ((this._PaidApplication != value))
				{
					this._PaidApplication = value;
				}
			}
		}
	}
	
	public partial class ABPrc_CreateOrderNumberResult
	{
		
		private string _OrderNumber;
		
		public ABPrc_CreateOrderNumberResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", DbType="VarChar(20)")]
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this._OrderNumber = value;
				}
			}
		}
	}
	
	public partial class ABproc_CheckuserLoginResult
	{
		
		private int _ID;
		
		private string _UserName;
		
		private string _Password;
		
		private System.Nullable<bool> _Status;
		
		private System.Nullable<bool> _Settle;
		
		private System.Nullable<bool> _Balance;
		
		private bool _IsAdmin;
		
		private decimal _BalanceAmount;
		
		private int _LoginResult;
		
		public ABproc_CheckuserLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Settle", DbType="Bit")]
		public System.Nullable<bool> Settle
		{
			get
			{
				return this._Settle;
			}
			set
			{
				if ((this._Settle != value))
				{
					this._Settle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Bit")]
		public System.Nullable<bool> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit NOT NULL")]
		public bool IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this._IsAdmin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceAmount", DbType="Decimal(12,2) NOT NULL")]
		public decimal BalanceAmount
		{
			get
			{
				return this._BalanceAmount;
			}
			set
			{
				if ((this._BalanceAmount != value))
				{
					this._BalanceAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginResult", DbType="Int NOT NULL")]
		public int LoginResult
		{
			get
			{
				return this._LoginResult;
			}
			set
			{
				if ((this._LoginResult != value))
				{
					this._LoginResult = value;
				}
			}
		}
	}
	
	public partial class Prc_AdminPanelMenuResult
	{
		
		private int _ID;
		
		private string _PageName;
		
		private string _URL;
		
		private int _Show;
		
		public Prc_AdminPanelMenuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageName", DbType="NVarChar(100)")]
		public string PageName
		{
			get
			{
				return this._PageName;
			}
			set
			{
				if ((this._PageName != value))
				{
					this._PageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(500)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this._URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Show", DbType="Int NOT NULL")]
		public int Show
		{
			get
			{
				return this._Show;
			}
			set
			{
				if ((this._Show != value))
				{
					this._Show = value;
				}
			}
		}
	}
	
	public partial class Prc_AdminPanelPageListResult
	{
		
		private int _ID;
		
		private string _PageName;
		
		private string _URL;
		
		private bool _Status;
		
		private int _PermissionID;
		
		private int _PageID;
		
		private int _AdminID;
		
		private bool _IsActive;
		
		public Prc_AdminPanelPageListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageName", DbType="NVarChar(100)")]
		public string PageName
		{
			get
			{
				return this._PageName;
			}
			set
			{
				if ((this._PageName != value))
				{
					this._PageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(500)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this._URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionID", DbType="Int NOT NULL")]
		public int PermissionID
		{
			get
			{
				return this._PermissionID;
			}
			set
			{
				if ((this._PermissionID != value))
				{
					this._PermissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageID", DbType="Int NOT NULL")]
		public int PageID
		{
			get
			{
				return this._PageID;
			}
			set
			{
				if ((this._PageID != value))
				{
					this._PageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminID", DbType="Int NOT NULL")]
		public int AdminID
		{
			get
			{
				return this._AdminID;
			}
			set
			{
				if ((this._AdminID != value))
				{
					this._AdminID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
	}
	
	public partial class Prc_AdminPanelPagePermissionCheckResult
	{
		
		private int _PermissionStatus;
		
		public Prc_AdminPanelPagePermissionCheckResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionStatus", DbType="Int NOT NULL")]
		public int PermissionStatus
		{
			get
			{
				return this._PermissionStatus;
			}
			set
			{
				if ((this._PermissionStatus != value))
				{
					this._PermissionStatus = value;
				}
			}
		}
	}
	
	public partial class Prc_CategoryListResult
	{
		
		private int _ID;
		
		private string _CategoryName;
		
		private string _ApplyFor;
		
		private int _AllotmentCount;
		
		public Prc_CategoryListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="VarChar(200)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyFor", DbType="VarChar(100)")]
		public string ApplyFor
		{
			get
			{
				return this._ApplyFor;
			}
			set
			{
				if ((this._ApplyFor != value))
				{
					this._ApplyFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllotmentCount", DbType="Int NOT NULL")]
		public int AllotmentCount
		{
			get
			{
				return this._AllotmentCount;
			}
			set
			{
				if ((this._AllotmentCount != value))
				{
					this._AllotmentCount = value;
				}
			}
		}
	}
	
	public partial class Prc_CategoryWiseApplicationResult
	{
		
		private string _CategoryName;
		
		private System.Nullable<int> _EWSCount;
		
		private System.Nullable<int> _LIGCount;
		
		public Prc_CategoryWiseApplicationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="VarChar(200)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EWSCount", DbType="Int")]
		public System.Nullable<int> EWSCount
		{
			get
			{
				return this._EWSCount;
			}
			set
			{
				if ((this._EWSCount != value))
				{
					this._EWSCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGCount", DbType="Int")]
		public System.Nullable<int> LIGCount
		{
			get
			{
				return this._LIGCount;
			}
			set
			{
				if ((this._LIGCount != value))
				{
					this._LIGCount = value;
				}
			}
		}
	}
	
	public partial class Prc_CategoryWisePlotAllotmentResult
	{
		
		private string _CategoryName;
		
		private System.Nullable<int> _EWSCount;
		
		private System.Nullable<int> _LIGCount;
		
		public Prc_CategoryWisePlotAllotmentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="VarChar(200)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EWSCount", DbType="Int")]
		public System.Nullable<int> EWSCount
		{
			get
			{
				return this._EWSCount;
			}
			set
			{
				if ((this._EWSCount != value))
				{
					this._EWSCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIGCount", DbType="Int")]
		public System.Nullable<int> LIGCount
		{
			get
			{
				return this._LIGCount;
			}
			set
			{
				if ((this._LIGCount != value))
				{
					this._LIGCount = value;
				}
			}
		}
	}
	
	public partial class Prc_ContactListResult
	{
		
		private int _ID;
		
		private string _CustomerName;
		
		private string _SrNo;
		
		private string _RelationName;
		
		private int _RegNo;
		
		private bool _Alloty;
		
		private bool _Status;
		
		private string _PlotNo;
		
		private int _RegID;
		
		private string _Contact;
		
		private string _Email_ID;
		
		private string _AadhaarNumber;
		
		private int _FormStatus;
		
		private string _RejectRemark;
		
		private string _ApplyFor;
		
		private string _Category;
		
		private string _Relation;
		
		public Prc_ContactListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(100)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrNo", DbType="VarChar(50)")]
		public string SrNo
		{
			get
			{
				return this._SrNo;
			}
			set
			{
				if ((this._SrNo != value))
				{
					this._SrNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationName", DbType="VarChar(100)")]
		public string RelationName
		{
			get
			{
				return this._RelationName;
			}
			set
			{
				if ((this._RelationName != value))
				{
					this._RelationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegNo", DbType="Int NOT NULL")]
		public int RegNo
		{
			get
			{
				return this._RegNo;
			}
			set
			{
				if ((this._RegNo != value))
				{
					this._RegNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alloty", DbType="Bit NOT NULL")]
		public bool Alloty
		{
			get
			{
				return this._Alloty;
			}
			set
			{
				if ((this._Alloty != value))
				{
					this._Alloty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlotNo", DbType="VarChar(100)")]
		public string PlotNo
		{
			get
			{
				return this._PlotNo;
			}
			set
			{
				if ((this._PlotNo != value))
				{
					this._PlotNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegID", DbType="Int NOT NULL")]
		public int RegID
		{
			get
			{
				return this._RegID;
			}
			set
			{
				if ((this._RegID != value))
				{
					this._RegID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(20)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this._Contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_ID", DbType="VarChar(100)")]
		public string Email_ID
		{
			get
			{
				return this._Email_ID;
			}
			set
			{
				if ((this._Email_ID != value))
				{
					this._Email_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AadhaarNumber", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string AadhaarNumber
		{
			get
			{
				return this._AadhaarNumber;
			}
			set
			{
				if ((this._AadhaarNumber != value))
				{
					this._AadhaarNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormStatus", DbType="Int NOT NULL")]
		public int FormStatus
		{
			get
			{
				return this._FormStatus;
			}
			set
			{
				if ((this._FormStatus != value))
				{
					this._FormStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RejectRemark", DbType="VarChar(1000)")]
		public string RejectRemark
		{
			get
			{
				return this._RejectRemark;
			}
			set
			{
				if ((this._RejectRemark != value))
				{
					this._RejectRemark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyFor", DbType="VarChar(100)")]
		public string ApplyFor
		{
			get
			{
				return this._ApplyFor;
			}
			set
			{
				if ((this._ApplyFor != value))
				{
					this._ApplyFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(200)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Relation", DbType="VarChar(100)")]
		public string Relation
		{
			get
			{
				return this._Relation;
			}
			set
			{
				if ((this._Relation != value))
				{
					this._Relation = value;
				}
			}
		}
	}
	
	public partial class Prc_Create_OrderNumberResult
	{
		
		private string _OrderNumber;
		
		public Prc_Create_OrderNumberResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", DbType="VarChar(20)")]
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this._OrderNumber = value;
				}
			}
		}
	}
	
	public partial class Prc_DisctinctLotteryNoResult
	{
		
		private int _TrialNo;
		
		public Prc_DisctinctLotteryNoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrialNo", DbType="Int NOT NULL")]
		public int TrialNo
		{
			get
			{
				return this._TrialNo;
			}
			set
			{
				if ((this._TrialNo != value))
				{
					this._TrialNo = value;
				}
			}
		}
	}
	
	public partial class Prc_FormCategoryDisctinctResult
	{
		
		private string _CategoryName;
		
		public Prc_FormCategoryDisctinctResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="VarChar(200)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
	}
	
	public partial class Prc_FormlistResult
	{
		
		private int _ID;
		
		private string _CustomerName;
		
		private string _SrNo;
		
		private string _RelationName;
		
		private int _RegNo;
		
		private bool _Alloty;
		
		private bool _Status;
		
		private string _PlotNo;
		
		private int _RegID;
		
		private int _FormStatus;
		
		private string _RejectRemark;
		
		private string _PlotCategory;
		
		private string _ApplicantCategory;
		
		public Prc_FormlistResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(100)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrNo", DbType="VarChar(50)")]
		public string SrNo
		{
			get
			{
				return this._SrNo;
			}
			set
			{
				if ((this._SrNo != value))
				{
					this._SrNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationName", DbType="VarChar(100)")]
		public string RelationName
		{
			get
			{
				return this._RelationName;
			}
			set
			{
				if ((this._RelationName != value))
				{
					this._RelationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegNo", DbType="Int NOT NULL")]
		public int RegNo
		{
			get
			{
				return this._RegNo;
			}
			set
			{
				if ((this._RegNo != value))
				{
					this._RegNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alloty", DbType="Bit NOT NULL")]
		public bool Alloty
		{
			get
			{
				return this._Alloty;
			}
			set
			{
				if ((this._Alloty != value))
				{
					this._Alloty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlotNo", DbType="VarChar(100)")]
		public string PlotNo
		{
			get
			{
				return this._PlotNo;
			}
			set
			{
				if ((this._PlotNo != value))
				{
					this._PlotNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegID", DbType="Int NOT NULL")]
		public int RegID
		{
			get
			{
				return this._RegID;
			}
			set
			{
				if ((this._RegID != value))
				{
					this._RegID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormStatus", DbType="Int NOT NULL")]
		public int FormStatus
		{
			get
			{
				return this._FormStatus;
			}
			set
			{
				if ((this._FormStatus != value))
				{
					this._FormStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RejectRemark", DbType="VarChar(1000)")]
		public string RejectRemark
		{
			get
			{
				return this._RejectRemark;
			}
			set
			{
				if ((this._RejectRemark != value))
				{
					this._RejectRemark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlotCategory", DbType="VarChar(100)")]
		public string PlotCategory
		{
			get
			{
				return this._PlotCategory;
			}
			set
			{
				if ((this._PlotCategory != value))
				{
					this._PlotCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicantCategory", DbType="VarChar(200)")]
		public string ApplicantCategory
		{
			get
			{
				return this._ApplicantCategory;
			}
			set
			{
				if ((this._ApplicantCategory != value))
				{
					this._ApplicantCategory = value;
				}
			}
		}
	}
	
	public partial class Prc_FormListCategoryWiseResult
	{
		
		private int _ID;
		
		private string _CustomerName;
		
		private string _SrNo;
		
		private string _Father;
		
		private int _RegNo;
		
		private bool _Alloty;
		
		private bool _Status;
		
		private int _RegID;
		
		private int _FormStatus;
		
		private string _RejectRemark;
		
		private string _PlotNo;
		
		private string _PlotCategory;
		
		private string _ApplicantCategory;
		
		public Prc_FormListCategoryWiseResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(100)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SrNo", DbType="VarChar(50)")]
		public string SrNo
		{
			get
			{
				return this._SrNo;
			}
			set
			{
				if ((this._SrNo != value))
				{
					this._SrNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Father", DbType="VarChar(100)")]
		public string Father
		{
			get
			{
				return this._Father;
			}
			set
			{
				if ((this._Father != value))
				{
					this._Father = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegNo", DbType="Int NOT NULL")]
		public int RegNo
		{
			get
			{
				return this._RegNo;
			}
			set
			{
				if ((this._RegNo != value))
				{
					this._RegNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alloty", DbType="Bit NOT NULL")]
		public bool Alloty
		{
			get
			{
				return this._Alloty;
			}
			set
			{
				if ((this._Alloty != value))
				{
					this._Alloty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegID", DbType="Int NOT NULL")]
		public int RegID
		{
			get
			{
				return this._RegID;
			}
			set
			{
				if ((this._RegID != value))
				{
					this._RegID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormStatus", DbType="Int NOT NULL")]
		public int FormStatus
		{
			get
			{
				return this._FormStatus;
			}
			set
			{
				if ((this._FormStatus != value))
				{
					this._FormStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RejectRemark", DbType="VarChar(1000)")]
		public string RejectRemark
		{
			get
			{
				return this._RejectRemark;
			}
			set
			{
				if ((this._RejectRemark != value))
				{
					this._RejectRemark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlotNo", DbType="VarChar(100)")]
		public string PlotNo
		{
			get
			{
				return this._PlotNo;
			}
			set
			{
				if ((this._PlotNo != value))
				{
					this._PlotNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlotCategory", DbType="VarChar(100)")]
		public string PlotCategory
		{
			get
			{
				return this._PlotCategory;
			}
			set
			{
				if ((this._PlotCategory != value))
				{
					this._PlotCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicantCategory", DbType="VarChar(200)")]
		public string ApplicantCategory
		{
			get
			{
				return this._ApplicantCategory;
			}
			set
			{
				if ((this._ApplicantCategory != value))
				{
					this._ApplicantCategory = value;
				}
			}
		}
	}
	
	public partial class Prc_FormlistExportResult
	{
		
		private System.Nullable<long> _RowNum;
		
		private int _RegNo;
		
		private string _CustomerName;
		
		private string _RelationName;
		
		private string _MobileNumber;
		
		private string _PlotCategory;
		
		private string _ApplicantCategory;
		
		private string _FormStatus;
		
		private string _RejectRemark;
		
		public Prc_FormlistExportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="BigInt")]
		public System.Nullable<long> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegNo", DbType="Int NOT NULL")]
		public int RegNo
		{
			get
			{
				return this._RegNo;
			}
			set
			{
				if ((this._RegNo != value))
				{
					this._RegNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(100)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationName", DbType="VarChar(100)")]
		public string RelationName
		{
			get
			{
				return this._RelationName;
			}
			set
			{
				if ((this._RelationName != value))
				{
					this._RelationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNumber", DbType="VarChar(20)")]
		public string MobileNumber
		{
			get
			{
				return this._MobileNumber;
			}
			set
			{
				if ((this._MobileNumber != value))
				{
					this._MobileNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlotCategory", DbType="VarChar(100)")]
		public string PlotCategory
		{
			get
			{
				return this._PlotCategory;
			}
			set
			{
				if ((this._PlotCategory != value))
				{
					this._PlotCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicantCategory", DbType="VarChar(200)")]
		public string ApplicantCategory
		{
			get
			{
				return this._ApplicantCategory;
			}
			set
			{
				if ((this._ApplicantCategory != value))
				{
					this._ApplicantCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormStatus", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string FormStatus
		{
			get
			{
				return this._FormStatus;
			}
			set
			{
				if ((this._FormStatus != value))
				{
					this._FormStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RejectRemark", DbType="VarChar(1000)")]
		public string RejectRemark
		{
			get
			{
				return this._RejectRemark;
			}
			set
			{
				if ((this._RejectRemark != value))
				{
					this._RejectRemark = value;
				}
			}
		}
	}
	
	public partial class Prc_GeneralSettingDetailsResult
	{
		
		private int _ID;
		
		private int _IsFinalLottery;
		
		private System.DateTime _NextLotteryTime;
		
		public Prc_GeneralSettingDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFinalLottery", DbType="Int NOT NULL")]
		public int IsFinalLottery
		{
			get
			{
				return this._IsFinalLottery;
			}
			set
			{
				if ((this._IsFinalLottery != value))
				{
					this._IsFinalLottery = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextLotteryTime", DbType="DateTime NOT NULL")]
		public System.DateTime NextLotteryTime
		{
			get
			{
				return this._NextLotteryTime;
			}
			set
			{
				if ((this._NextLotteryTime != value))
				{
					this._NextLotteryTime = value;
				}
			}
		}
	}
	
	public partial class Prc_RegisterListResult
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _Contact;
		
		private string _Email_ID;
		
		private string _Gender;
		
		private string _DOB;
		
		private string _Relation;
		
		private string _RelationName;
		
		private string _IDName;
		
		private string _IDValues;
		
		private string _AadhaarNumber;
		
		private string _Category;
		
		private string _AnnulIncome;
		
		private string _Address;
		
		private string _Country;
		
		private string _State;
		
		private string _City;
		
		private string _Pincode;
		
		private bool _Status;
		
		private System.DateTime _insertDate;
		
		private string _ApplyFor;
		
		private bool _Payment_Status;
		
		private decimal _DDAmount;
		
		private string _DDNumber;
		
		private string _BankName;
		
		private string _DDReturnToName;
		
		private string _DDReturnIDName;
		
		private string _DDReturnIDValue;
		
		private int _DDReturn;
		
		private System.Nullable<System.DateTime> _DDReturnDate;
		
		public Prc_RegisterListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(20)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this._Contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_ID", DbType="VarChar(100)")]
		public string Email_ID
		{
			get
			{
				return this._Email_ID;
			}
			set
			{
				if ((this._Email_ID != value))
				{
					this._Email_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(100)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="VarChar(100)")]
		public string DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this._DOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Relation", DbType="VarChar(100)")]
		public string Relation
		{
			get
			{
				return this._Relation;
			}
			set
			{
				if ((this._Relation != value))
				{
					this._Relation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationName", DbType="VarChar(100)")]
		public string RelationName
		{
			get
			{
				return this._RelationName;
			}
			set
			{
				if ((this._RelationName != value))
				{
					this._RelationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDName", DbType="VarChar(100)")]
		public string IDName
		{
			get
			{
				return this._IDName;
			}
			set
			{
				if ((this._IDName != value))
				{
					this._IDName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDValues", DbType="VarChar(100)")]
		public string IDValues
		{
			get
			{
				return this._IDValues;
			}
			set
			{
				if ((this._IDValues != value))
				{
					this._IDValues = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AadhaarNumber", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string AadhaarNumber
		{
			get
			{
				return this._AadhaarNumber;
			}
			set
			{
				if ((this._AadhaarNumber != value))
				{
					this._AadhaarNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(200)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnulIncome", DbType="VarChar(100)")]
		public string AnnulIncome
		{
			get
			{
				return this._AnnulIncome;
			}
			set
			{
				if ((this._AnnulIncome != value))
				{
					this._AnnulIncome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(2000)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(50)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pincode", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Pincode
		{
			get
			{
				return this._Pincode;
			}
			set
			{
				if ((this._Pincode != value))
				{
					this._Pincode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insertDate", DbType="DateTime NOT NULL")]
		public System.DateTime insertDate
		{
			get
			{
				return this._insertDate;
			}
			set
			{
				if ((this._insertDate != value))
				{
					this._insertDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyFor", DbType="VarChar(100)")]
		public string ApplyFor
		{
			get
			{
				return this._ApplyFor;
			}
			set
			{
				if ((this._ApplyFor != value))
				{
					this._ApplyFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Status", DbType="Bit NOT NULL")]
		public bool Payment_Status
		{
			get
			{
				return this._Payment_Status;
			}
			set
			{
				if ((this._Payment_Status != value))
				{
					this._Payment_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDAmount", DbType="Decimal(12,2) NOT NULL")]
		public decimal DDAmount
		{
			get
			{
				return this._DDAmount;
			}
			set
			{
				if ((this._DDAmount != value))
				{
					this._DDAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDNumber", DbType="VarChar(100)")]
		public string DDNumber
		{
			get
			{
				return this._DDNumber;
			}
			set
			{
				if ((this._DDNumber != value))
				{
					this._DDNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="VarChar(100)")]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this._BankName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDReturnToName", DbType="VarChar(200)")]
		public string DDReturnToName
		{
			get
			{
				return this._DDReturnToName;
			}
			set
			{
				if ((this._DDReturnToName != value))
				{
					this._DDReturnToName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDReturnIDName", DbType="VarChar(200)")]
		public string DDReturnIDName
		{
			get
			{
				return this._DDReturnIDName;
			}
			set
			{
				if ((this._DDReturnIDName != value))
				{
					this._DDReturnIDName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDReturnIDValue", DbType="VarChar(200)")]
		public string DDReturnIDValue
		{
			get
			{
				return this._DDReturnIDValue;
			}
			set
			{
				if ((this._DDReturnIDValue != value))
				{
					this._DDReturnIDValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDReturn", DbType="Int NOT NULL")]
		public int DDReturn
		{
			get
			{
				return this._DDReturn;
			}
			set
			{
				if ((this._DDReturn != value))
				{
					this._DDReturn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDReturnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DDReturnDate
		{
			get
			{
				return this._DDReturnDate;
			}
			set
			{
				if ((this._DDReturnDate != value))
				{
					this._DDReturnDate = value;
				}
			}
		}
	}
	
	public partial class Prc_TrailNoListWithSeedResult
	{
		
		private int _ID;
		
		private string _TrialNo;
		
		private string _SeedNo;
		
		public Prc_TrailNoListWithSeedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrialNo", DbType="VarChar(100)")]
		public string TrialNo
		{
			get
			{
				return this._TrialNo;
			}
			set
			{
				if ((this._TrialNo != value))
				{
					this._TrialNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeedNo", DbType="VarChar(100)")]
		public string SeedNo
		{
			get
			{
				return this._SeedNo;
			}
			set
			{
				if ((this._SeedNo != value))
				{
					this._SeedNo = value;
				}
			}
		}
	}
	
	public partial class Prc_TransactionlistResult
	{
		
		private int _ID;
		
		private int _CustomerID;
		
		private int _RegID;
		
		private string _FormID;
		
		private string _Order_ID;
		
		private decimal _Total_Price;
		
		private bool _Payment_Status;
		
		private decimal _AmountReceived;
		
		private decimal _RefundAmount;
		
		private string _RefundDetail;
		
		private System.DateTime _insertDate;
		
		private System.Nullable<System.DateTime> _PaymentDate;
		
		private System.Nullable<System.DateTime> _RefundDate;
		
		private string _Email_ID;
		
		private string _Gender;
		
		private string _DOB;
		
		private string _IDName;
		
		private string _IDValues;
		
		private string _AadhaarNumber;
		
		private string _AnnulIncome;
		
		private string _Address;
		
		private string _Country;
		
		private string _State;
		
		private string _City;
		
		private string _Pincode;
		
		private bool _Status;
		
		private System.DateTime _insertDate1;
		
		private string _CustomerName;
		
		private string _Contact;
		
		private string _ApplyFor;
		
		private string _RelationName;
		
		private string _Relation;
		
		private string _Category;
		
		private string _BankName;
		
		private string _AccountHolderName;
		
		private string _IFSCCode;
		
		private string _BankAddress;
		
		private decimal _DDAmount;
		
		private string _DDNumber;
		
		private string _BankAccountNumber;
		
		private System.Nullable<System.DateTime> _DDReturnDate;
		
		private string _DDReturnToName;
		
		private string _DDReturnIDName;
		
		private string _DDReturnIDValue;
		
		private string _DDDepositer;
		
		private string _DDDepositerID;
		
		private string _DDDepositerIDNo;
		
		private string _DDDepositorRelation;
		
		public Prc_TransactionlistResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this._CustomerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegID", DbType="Int NOT NULL")]
		public int RegID
		{
			get
			{
				return this._RegID;
			}
			set
			{
				if ((this._RegID != value))
				{
					this._RegID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="VarChar(100)")]
		public string FormID
		{
			get
			{
				return this._FormID;
			}
			set
			{
				if ((this._FormID != value))
				{
					this._FormID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_ID", DbType="NVarChar(100)")]
		public string Order_ID
		{
			get
			{
				return this._Order_ID;
			}
			set
			{
				if ((this._Order_ID != value))
				{
					this._Order_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Price", DbType="Decimal(12,2) NOT NULL")]
		public decimal Total_Price
		{
			get
			{
				return this._Total_Price;
			}
			set
			{
				if ((this._Total_Price != value))
				{
					this._Total_Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment_Status", DbType="Bit NOT NULL")]
		public bool Payment_Status
		{
			get
			{
				return this._Payment_Status;
			}
			set
			{
				if ((this._Payment_Status != value))
				{
					this._Payment_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountReceived", DbType="Decimal(12,2) NOT NULL")]
		public decimal AmountReceived
		{
			get
			{
				return this._AmountReceived;
			}
			set
			{
				if ((this._AmountReceived != value))
				{
					this._AmountReceived = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefundAmount", DbType="Decimal(12,2) NOT NULL")]
		public decimal RefundAmount
		{
			get
			{
				return this._RefundAmount;
			}
			set
			{
				if ((this._RefundAmount != value))
				{
					this._RefundAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefundDetail", DbType="VarChar(2000)")]
		public string RefundDetail
		{
			get
			{
				return this._RefundDetail;
			}
			set
			{
				if ((this._RefundDetail != value))
				{
					this._RefundDetail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insertDate", DbType="DateTime NOT NULL")]
		public System.DateTime insertDate
		{
			get
			{
				return this._insertDate;
			}
			set
			{
				if ((this._insertDate != value))
				{
					this._insertDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PaymentDate
		{
			get
			{
				return this._PaymentDate;
			}
			set
			{
				if ((this._PaymentDate != value))
				{
					this._PaymentDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefundDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RefundDate
		{
			get
			{
				return this._RefundDate;
			}
			set
			{
				if ((this._RefundDate != value))
				{
					this._RefundDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_ID", DbType="VarChar(100)")]
		public string Email_ID
		{
			get
			{
				return this._Email_ID;
			}
			set
			{
				if ((this._Email_ID != value))
				{
					this._Email_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(100)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="VarChar(100)")]
		public string DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this._DOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDName", DbType="VarChar(100)")]
		public string IDName
		{
			get
			{
				return this._IDName;
			}
			set
			{
				if ((this._IDName != value))
				{
					this._IDName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDValues", DbType="VarChar(100)")]
		public string IDValues
		{
			get
			{
				return this._IDValues;
			}
			set
			{
				if ((this._IDValues != value))
				{
					this._IDValues = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AadhaarNumber", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string AadhaarNumber
		{
			get
			{
				return this._AadhaarNumber;
			}
			set
			{
				if ((this._AadhaarNumber != value))
				{
					this._AadhaarNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnulIncome", DbType="VarChar(100)")]
		public string AnnulIncome
		{
			get
			{
				return this._AnnulIncome;
			}
			set
			{
				if ((this._AnnulIncome != value))
				{
					this._AnnulIncome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(2000)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(50)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pincode", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Pincode
		{
			get
			{
				return this._Pincode;
			}
			set
			{
				if ((this._Pincode != value))
				{
					this._Pincode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insertDate1", DbType="DateTime NOT NULL")]
		public System.DateTime insertDate1
		{
			get
			{
				return this._insertDate1;
			}
			set
			{
				if ((this._insertDate1 != value))
				{
					this._insertDate1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(100)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(20)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this._Contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplyFor", DbType="VarChar(100)")]
		public string ApplyFor
		{
			get
			{
				return this._ApplyFor;
			}
			set
			{
				if ((this._ApplyFor != value))
				{
					this._ApplyFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationName", DbType="VarChar(100)")]
		public string RelationName
		{
			get
			{
				return this._RelationName;
			}
			set
			{
				if ((this._RelationName != value))
				{
					this._RelationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Relation", DbType="VarChar(100)")]
		public string Relation
		{
			get
			{
				return this._Relation;
			}
			set
			{
				if ((this._Relation != value))
				{
					this._Relation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(200)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="VarChar(100)")]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this._BankName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountHolderName", DbType="VarChar(100)")]
		public string AccountHolderName
		{
			get
			{
				return this._AccountHolderName;
			}
			set
			{
				if ((this._AccountHolderName != value))
				{
					this._AccountHolderName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFSCCode", DbType="VarChar(100)")]
		public string IFSCCode
		{
			get
			{
				return this._IFSCCode;
			}
			set
			{
				if ((this._IFSCCode != value))
				{
					this._IFSCCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAddress", DbType="VarChar(2000)")]
		public string BankAddress
		{
			get
			{
				return this._BankAddress;
			}
			set
			{
				if ((this._BankAddress != value))
				{
					this._BankAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDAmount", DbType="Decimal(12,2) NOT NULL")]
		public decimal DDAmount
		{
			get
			{
				return this._DDAmount;
			}
			set
			{
				if ((this._DDAmount != value))
				{
					this._DDAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDNumber", DbType="VarChar(100)")]
		public string DDNumber
		{
			get
			{
				return this._DDNumber;
			}
			set
			{
				if ((this._DDNumber != value))
				{
					this._DDNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccountNumber", DbType="VarChar(100)")]
		public string BankAccountNumber
		{
			get
			{
				return this._BankAccountNumber;
			}
			set
			{
				if ((this._BankAccountNumber != value))
				{
					this._BankAccountNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDReturnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DDReturnDate
		{
			get
			{
				return this._DDReturnDate;
			}
			set
			{
				if ((this._DDReturnDate != value))
				{
					this._DDReturnDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDReturnToName", DbType="VarChar(200)")]
		public string DDReturnToName
		{
			get
			{
				return this._DDReturnToName;
			}
			set
			{
				if ((this._DDReturnToName != value))
				{
					this._DDReturnToName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDReturnIDName", DbType="VarChar(200)")]
		public string DDReturnIDName
		{
			get
			{
				return this._DDReturnIDName;
			}
			set
			{
				if ((this._DDReturnIDName != value))
				{
					this._DDReturnIDName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDReturnIDValue", DbType="VarChar(200)")]
		public string DDReturnIDValue
		{
			get
			{
				return this._DDReturnIDValue;
			}
			set
			{
				if ((this._DDReturnIDValue != value))
				{
					this._DDReturnIDValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDDepositer", DbType="VarChar(100)")]
		public string DDDepositer
		{
			get
			{
				return this._DDDepositer;
			}
			set
			{
				if ((this._DDDepositer != value))
				{
					this._DDDepositer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDDepositerID", DbType="VarChar(100)")]
		public string DDDepositerID
		{
			get
			{
				return this._DDDepositerID;
			}
			set
			{
				if ((this._DDDepositerID != value))
				{
					this._DDDepositerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDDepositerIDNo", DbType="VarChar(100)")]
		public string DDDepositerIDNo
		{
			get
			{
				return this._DDDepositerIDNo;
			}
			set
			{
				if ((this._DDDepositerIDNo != value))
				{
					this._DDDepositerIDNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDDepositorRelation", DbType="VarChar(100)")]
		public string DDDepositorRelation
		{
			get
			{
				return this._DDDepositorRelation;
			}
			set
			{
				if ((this._DDDepositorRelation != value))
				{
					this._DDDepositorRelation = value;
				}
			}
		}
	}
	
	public partial class Prc_TrialLotteryListResult
	{
		
		private int _ID;
		
		private string _CustomerName;
		
		private string _Father;
		
		private string _RegNo;
		
		private string _PlotNo;
		
		private string _PlotCategory;
		
		private string _ApplicantCategory;
		
		private int _TrialNo;
		
		public Prc_TrialLotteryListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(100)")]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this._CustomerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Father", DbType="VarChar(100)")]
		public string Father
		{
			get
			{
				return this._Father;
			}
			set
			{
				if ((this._Father != value))
				{
					this._Father = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegNo", DbType="VarChar(100)")]
		public string RegNo
		{
			get
			{
				return this._RegNo;
			}
			set
			{
				if ((this._RegNo != value))
				{
					this._RegNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlotNo", DbType="VarChar(100)")]
		public string PlotNo
		{
			get
			{
				return this._PlotNo;
			}
			set
			{
				if ((this._PlotNo != value))
				{
					this._PlotNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlotCategory", DbType="VarChar(100)")]
		public string PlotCategory
		{
			get
			{
				return this._PlotCategory;
			}
			set
			{
				if ((this._PlotCategory != value))
				{
					this._PlotCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicantCategory", DbType="VarChar(100)")]
		public string ApplicantCategory
		{
			get
			{
				return this._ApplicantCategory;
			}
			set
			{
				if ((this._ApplicantCategory != value))
				{
					this._ApplicantCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrialNo", DbType="Int NOT NULL")]
		public int TrialNo
		{
			get
			{
				return this._TrialNo;
			}
			set
			{
				if ((this._TrialNo != value))
				{
					this._TrialNo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
